stages:
  data_ingestion:
    cmd: python emotion_detection/data_ingestion.py
    deps:
    - emotion_detection/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python emotion_detection/data_preprocessing.py
    deps:
    - data/raw
    - emotion_detection/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python emotion_detection/feature_engineering.py
    deps:
    - data/interim
    - emotion_detection/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
  model_building:
    cmd: python emotion_detection/model_building.py
    deps:
    - data/processed
    - emotion_detection/model_building.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    outs:
    - models
  model_evaluation:
    cmd: python emotion_detection/model_evaluation.py
    deps:
    - emotion_detection/model_evaluation.py
    - models
    metrics:
    - metrics.json
